### AddUser
POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{"username": "johnny", "age": "28"}

### GetUsers
GET http://localhost:8080/user

### GetLocations
GET http://localhost:8080/locations

### GetSingleUser
GET http://localhost:8080/user/2c25cc2f-ddb3-4a01-95da-565416ba53a0

### UpdateUser
PUT http://localhost:8080/user/990a10dd-5689-42c7-8530-4304e8952c98
Content-Type: application/json
Accept: application/json

{"username": "johnny", "age": "31"}

### DeleteUser
DELETE http://localhost:8080/user/990a10dd-5689-42c7-8530-4304e8952c98
