### AddUser
POST http://localhost:8080/user
Content-Type: application/json
Accept: application/json

{"username": "johnny", "age": "28"}

### GetUsers
GET http://localhost:8080/user

### GetLocations
GET http://localhost:8080/locations

### GetSingleUser
GET http://localhost:8080/user/26cc811e-9da3-4308-9284-0aa6480008ad

### UpdateUser
PUT http://localhost:8080/user/26cc811e-9da3-4308-9284-0aa6480008ad
Content-Type: application/json
Accept: application/json

{"username": "johnny", "age": "31"}

### DeleteUser
DELETE http://localhost:8080/user/26cc811e-9da3-4308-9284-0aa6480008ad
